spring:
  kafka:
    bootstrap-servers:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-1
      enable-auto-commit: true
      #auto-commit-interval: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest



#  indentity_map_capacity=1024
#  batch.size=8000
#  linger.ms=0
#  buffer.memory=10485760
#  consumer.timeout.ms=400
#  auto.offset.reset=earliest
#  connections.max.idle.ms=200000