#redis config start

redis:
  address:
    - ip: 127.0.0.1
      port: 6379
    - ip: 127.0.0.1
      port: 6380
  maxTotal: 20  #最大连接数
  maxIdle: 10  #最大空闲数
  minIdle: 2 #最小空闲数
  testOnBorrow: true  #从jedis连接池获取连接时，校验并返回可用的连接
  testOnReturn: false  #把连接放回jedis连接池时，校验并返回可用的连接
  host: 127.0.0.1
  port: 6379
  database: 2
  password:
  timeout: 10000
  maxWaitMillis: 1000

lock:
  redis:
    host: 127.0.0.1
    port: 6379
