// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/sky/hiwise/netty/tcp/Message.proto

package com.sky.hiwise.netty.tcp;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GroupMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GroupMessage.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <pre>
     *用data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GroupMessage.DataType data_type = 1;</code>
     * @return The dataType.
     */
    com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType getDataType();

    /**
     * <code>.Customer customer = 2;</code>
     * @return Whether the customer field is set.
     */
    boolean hasCustomer();
    /**
     * <code>.Customer customer = 2;</code>
     * @return The customer.
     */
    com.sky.hiwise.netty.tcp.Message.Customer getCustomer();
    /**
     * <code>.Customer customer = 2;</code>
     */
    com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder getCustomerOrBuilder();

    /**
     * <code>.Car car = 3;</code>
     * @return Whether the car field is set.
     */
    boolean hasCar();
    /**
     * <code>.Car car = 3;</code>
     * @return The car.
     */
    com.sky.hiwise.netty.tcp.Message.Car getCar();
    /**
     * <code>.Car car = 3;</code>
     */
    com.sky.hiwise.netty.tcp.Message.CarOrBuilder getCarOrBuilder();

    public com.sky.hiwise.netty.tcp.Message.GroupMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   *protobuf 可以使用message 管理其他的message
   * </pre>
   *
   * Protobuf type {@code GroupMessage}
   */
  public static final class GroupMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GroupMessage)
      GroupMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupMessage.newBuilder() to construct.
    private GroupMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupMessage() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              com.sky.hiwise.netty.tcp.Message.Customer.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.sky.hiwise.netty.tcp.Message.Customer) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.sky.hiwise.netty.tcp.Message.Customer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.sky.hiwise.netty.tcp.Message.Customer) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.sky.hiwise.netty.tcp.Message.Car.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.sky.hiwise.netty.tcp.Message.Car) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.sky.hiwise.netty.tcp.Message.Car.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.sky.hiwise.netty.tcp.Message.Car) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky.hiwise.netty.tcp.Message.internal_static_GroupMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky.hiwise.netty.tcp.Message.internal_static_GroupMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky.hiwise.netty.tcp.Message.GroupMessage.class, com.sky.hiwise.netty.tcp.Message.GroupMessage.Builder.class);
    }

    /**
     * <pre>
     *定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code GroupMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>CustomerType = 0;</code>
       */
      CustomerType(0),
      /**
       * <code>CarType = 1;</code>
       */
      CarType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>CustomerType = 0;</code>
       */
      public static final int CustomerType_VALUE = 0;
      /**
       * <code>CarType = 1;</code>
       */
      public static final int CarType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return CustomerType;
          case 1: return CarType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.sky.hiwise.netty.tcp.Message.GroupMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GroupMessage.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      CUSTOMER(2),
      CAR(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return CUSTOMER;
          case 3: return CAR;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *用data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GroupMessage.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *用data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GroupMessage.DataType data_type = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType result = com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType.valueOf(dataType_);
      return result == null ? com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType.UNRECOGNIZED : result;
    }

    public static final int CUSTOMER_FIELD_NUMBER = 2;
    /**
     * <code>.Customer customer = 2;</code>
     * @return Whether the customer field is set.
     */
    @java.lang.Override
    public boolean hasCustomer() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Customer customer = 2;</code>
     * @return The customer.
     */
    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.Customer getCustomer() {
      if (dataBodyCase_ == 2) {
         return (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_;
      }
      return com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
    }
    /**
     * <code>.Customer customer = 2;</code>
     */
    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder getCustomerOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_;
      }
      return com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
    }

    public static final int CAR_FIELD_NUMBER = 3;
    /**
     * <code>.Car car = 3;</code>
     * @return Whether the car field is set.
     */
    @java.lang.Override
    public boolean hasCar() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Car car = 3;</code>
     * @return The car.
     */
    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.Car getCar() {
      if (dataBodyCase_ == 3) {
         return (com.sky.hiwise.netty.tcp.Message.Car) dataBody_;
      }
      return com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
    }
    /**
     * <code>.Car car = 3;</code>
     */
    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.CarOrBuilder getCarOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.sky.hiwise.netty.tcp.Message.Car) dataBody_;
      }
      return com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType.CustomerType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.sky.hiwise.netty.tcp.Message.Car) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType.CustomerType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.sky.hiwise.netty.tcp.Message.Car) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sky.hiwise.netty.tcp.Message.GroupMessage)) {
        return super.equals(obj);
      }
      com.sky.hiwise.netty.tcp.Message.GroupMessage other = (com.sky.hiwise.netty.tcp.Message.GroupMessage) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getCustomer()
              .equals(other.getCustomer())) return false;
          break;
        case 3:
          if (!getCar()
              .equals(other.getCar())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
          hash = (53 * hash) + getCustomer().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CAR_FIELD_NUMBER;
          hash = (53 * hash) + getCar().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.GroupMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sky.hiwise.netty.tcp.Message.GroupMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protobuf 可以使用message 管理其他的message
     * </pre>
     *
     * Protobuf type {@code GroupMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GroupMessage)
        com.sky.hiwise.netty.tcp.Message.GroupMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_GroupMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_GroupMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sky.hiwise.netty.tcp.Message.GroupMessage.class, com.sky.hiwise.netty.tcp.Message.GroupMessage.Builder.class);
      }

      // Construct using com.sky.hiwise.netty.tcp.Message.GroupMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_GroupMessage_descriptor;
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.GroupMessage getDefaultInstanceForType() {
        return com.sky.hiwise.netty.tcp.Message.GroupMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.GroupMessage build() {
        com.sky.hiwise.netty.tcp.Message.GroupMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.GroupMessage buildPartial() {
        com.sky.hiwise.netty.tcp.Message.GroupMessage result = new com.sky.hiwise.netty.tcp.Message.GroupMessage(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (customerBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = customerBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (carBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = carBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sky.hiwise.netty.tcp.Message.GroupMessage) {
          return mergeFrom((com.sky.hiwise.netty.tcp.Message.GroupMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sky.hiwise.netty.tcp.Message.GroupMessage other) {
        if (other == com.sky.hiwise.netty.tcp.Message.GroupMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case CUSTOMER: {
            mergeCustomer(other.getCustomer());
            break;
          }
          case CAR: {
            mergeCar(other.getCar());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sky.hiwise.netty.tcp.Message.GroupMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sky.hiwise.netty.tcp.Message.GroupMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *用data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GroupMessage.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *用data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GroupMessage.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GroupMessage.DataType data_type = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType result = com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType.valueOf(dataType_);
        return result == null ? com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *用data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GroupMessage.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.sky.hiwise.netty.tcp.Message.GroupMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GroupMessage.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.sky.hiwise.netty.tcp.Message.Customer, com.sky.hiwise.netty.tcp.Message.Customer.Builder, com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder> customerBuilder_;
      /**
       * <code>.Customer customer = 2;</code>
       * @return Whether the customer field is set.
       */
      @java.lang.Override
      public boolean hasCustomer() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Customer customer = 2;</code>
       * @return The customer.
       */
      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Customer getCustomer() {
        if (customerBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_;
          }
          return com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return customerBuilder_.getMessage();
          }
          return com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
        }
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      public Builder setCustomer(com.sky.hiwise.netty.tcp.Message.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          customerBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      public Builder setCustomer(
          com.sky.hiwise.netty.tcp.Message.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          customerBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      public Builder mergeCustomer(com.sky.hiwise.netty.tcp.Message.Customer value) {
        if (customerBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance()) {
            dataBody_ = com.sky.hiwise.netty.tcp.Message.Customer.newBuilder((com.sky.hiwise.netty.tcp.Message.Customer) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            customerBuilder_.mergeFrom(value);
          }
          customerBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          customerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      public com.sky.hiwise.netty.tcp.Message.Customer.Builder getCustomerBuilder() {
        return getCustomerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder getCustomerOrBuilder() {
        if ((dataBodyCase_ == 2) && (customerBuilder_ != null)) {
          return customerBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_;
          }
          return com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
        }
      }
      /**
       * <code>.Customer customer = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sky.hiwise.netty.tcp.Message.Customer, com.sky.hiwise.netty.tcp.Message.Customer.Builder, com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
          }
          customerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sky.hiwise.netty.tcp.Message.Customer, com.sky.hiwise.netty.tcp.Message.Customer.Builder, com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder>(
                  (com.sky.hiwise.netty.tcp.Message.Customer) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return customerBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.sky.hiwise.netty.tcp.Message.Car, com.sky.hiwise.netty.tcp.Message.Car.Builder, com.sky.hiwise.netty.tcp.Message.CarOrBuilder> carBuilder_;
      /**
       * <code>.Car car = 3;</code>
       * @return Whether the car field is set.
       */
      @java.lang.Override
      public boolean hasCar() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Car car = 3;</code>
       * @return The car.
       */
      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Car getCar() {
        if (carBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.sky.hiwise.netty.tcp.Message.Car) dataBody_;
          }
          return com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return carBuilder_.getMessage();
          }
          return com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
        }
      }
      /**
       * <code>.Car car = 3;</code>
       */
      public Builder setCar(com.sky.hiwise.netty.tcp.Message.Car value) {
        if (carBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          carBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Car car = 3;</code>
       */
      public Builder setCar(
          com.sky.hiwise.netty.tcp.Message.Car.Builder builderForValue) {
        if (carBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          carBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Car car = 3;</code>
       */
      public Builder mergeCar(com.sky.hiwise.netty.tcp.Message.Car value) {
        if (carBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance()) {
            dataBody_ = com.sky.hiwise.netty.tcp.Message.Car.newBuilder((com.sky.hiwise.netty.tcp.Message.Car) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            carBuilder_.mergeFrom(value);
          }
          carBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Car car = 3;</code>
       */
      public Builder clearCar() {
        if (carBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          carBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Car car = 3;</code>
       */
      public com.sky.hiwise.netty.tcp.Message.Car.Builder getCarBuilder() {
        return getCarFieldBuilder().getBuilder();
      }
      /**
       * <code>.Car car = 3;</code>
       */
      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.CarOrBuilder getCarOrBuilder() {
        if ((dataBodyCase_ == 3) && (carBuilder_ != null)) {
          return carBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.sky.hiwise.netty.tcp.Message.Car) dataBody_;
          }
          return com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
        }
      }
      /**
       * <code>.Car car = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sky.hiwise.netty.tcp.Message.Car, com.sky.hiwise.netty.tcp.Message.Car.Builder, com.sky.hiwise.netty.tcp.Message.CarOrBuilder> 
          getCarFieldBuilder() {
        if (carBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
          }
          carBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sky.hiwise.netty.tcp.Message.Car, com.sky.hiwise.netty.tcp.Message.Car.Builder, com.sky.hiwise.netty.tcp.Message.CarOrBuilder>(
                  (com.sky.hiwise.netty.tcp.Message.Car) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return carBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GroupMessage)
    }

    // @@protoc_insertion_point(class_scope:GroupMessage)
    private static final com.sky.hiwise.netty.tcp.Message.GroupMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sky.hiwise.netty.tcp.Message.GroupMessage();
    }

    public static com.sky.hiwise.netty.tcp.Message.GroupMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupMessage>
        PARSER = new com.google.protobuf.AbstractParser<GroupMessage>() {
      @java.lang.Override
      public GroupMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.GroupMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Customer类的属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Customer}
   */
  public static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky.hiwise.netty.tcp.Message.internal_static_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky.hiwise.netty.tcp.Message.internal_static_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky.hiwise.netty.tcp.Message.Customer.class, com.sky.hiwise.netty.tcp.Message.Customer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *Customer类的属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sky.hiwise.netty.tcp.Message.Customer)) {
        return super.equals(obj);
      }
      com.sky.hiwise.netty.tcp.Message.Customer other = (com.sky.hiwise.netty.tcp.Message.Customer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sky.hiwise.netty.tcp.Message.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Customer)
        com.sky.hiwise.netty.tcp.Message.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sky.hiwise.netty.tcp.Message.Customer.class, com.sky.hiwise.netty.tcp.Message.Customer.Builder.class);
      }

      // Construct using com.sky.hiwise.netty.tcp.Message.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_Customer_descriptor;
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Customer getDefaultInstanceForType() {
        return com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Customer build() {
        com.sky.hiwise.netty.tcp.Message.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Customer buildPartial() {
        com.sky.hiwise.netty.tcp.Message.Customer result = new com.sky.hiwise.netty.tcp.Message.Customer(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sky.hiwise.netty.tcp.Message.Customer) {
          return mergeFrom((com.sky.hiwise.netty.tcp.Message.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sky.hiwise.netty.tcp.Message.Customer other) {
        if (other == com.sky.hiwise.netty.tcp.Message.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sky.hiwise.netty.tcp.Message.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sky.hiwise.netty.tcp.Message.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *Customer类的属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *Customer类的属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Customer类的属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Customer)
    }

    // @@protoc_insertion_point(class_scope:Customer)
    private static final com.sky.hiwise.netty.tcp.Message.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sky.hiwise.netty.tcp.Message.Customer();
    }

    public static com.sky.hiwise.netty.tcp.Message.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 clueId = 1;</code>
     * @return The clueId.
     */
    int getClueId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();
  }
  /**
   * Protobuf type {@code Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      title_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Car();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              clueId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky.hiwise.netty.tcp.Message.internal_static_Car_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky.hiwise.netty.tcp.Message.internal_static_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky.hiwise.netty.tcp.Message.Car.class, com.sky.hiwise.netty.tcp.Message.Car.Builder.class);
    }

    public static final int CLUEID_FIELD_NUMBER = 1;
    private int clueId_;
    /**
     * <code>int32 clueId = 1;</code>
     * @return The clueId.
     */
    @java.lang.Override
    public int getClueId() {
      return clueId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clueId_ != 0) {
        output.writeInt32(1, clueId_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clueId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clueId_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sky.hiwise.netty.tcp.Message.Car)) {
        return super.equals(obj);
      }
      com.sky.hiwise.netty.tcp.Message.Car other = (com.sky.hiwise.netty.tcp.Message.Car) obj;

      if (getClueId()
          != other.getClueId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLUEID_FIELD_NUMBER;
      hash = (53 * hash) + getClueId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sky.hiwise.netty.tcp.Message.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sky.hiwise.netty.tcp.Message.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Car)
        com.sky.hiwise.netty.tcp.Message.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sky.hiwise.netty.tcp.Message.Car.class, com.sky.hiwise.netty.tcp.Message.Car.Builder.class);
      }

      // Construct using com.sky.hiwise.netty.tcp.Message.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clueId_ = 0;

        title_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sky.hiwise.netty.tcp.Message.internal_static_Car_descriptor;
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Car getDefaultInstanceForType() {
        return com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance();
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Car build() {
        com.sky.hiwise.netty.tcp.Message.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sky.hiwise.netty.tcp.Message.Car buildPartial() {
        com.sky.hiwise.netty.tcp.Message.Car result = new com.sky.hiwise.netty.tcp.Message.Car(this);
        result.clueId_ = clueId_;
        result.title_ = title_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sky.hiwise.netty.tcp.Message.Car) {
          return mergeFrom((com.sky.hiwise.netty.tcp.Message.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sky.hiwise.netty.tcp.Message.Car other) {
        if (other == com.sky.hiwise.netty.tcp.Message.Car.getDefaultInstance()) return this;
        if (other.getClueId() != 0) {
          setClueId(other.getClueId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sky.hiwise.netty.tcp.Message.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sky.hiwise.netty.tcp.Message.Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int clueId_ ;
      /**
       * <code>int32 clueId = 1;</code>
       * @return The clueId.
       */
      @java.lang.Override
      public int getClueId() {
        return clueId_;
      }
      /**
       * <code>int32 clueId = 1;</code>
       * @param value The clueId to set.
       * @return This builder for chaining.
       */
      public Builder setClueId(int value) {
        
        clueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 clueId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClueId() {
        
        clueId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Car)
    }

    // @@protoc_insertion_point(class_scope:Car)
    private static final com.sky.hiwise.netty.tcp.Message.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sky.hiwise.netty.tcp.Message.Car();
    }

    public static com.sky.hiwise.netty.tcp.Message.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sky.hiwise.netty.tcp.Message.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&com/sky/hiwise/netty/tcp/Message.proto" +
      "\"\244\001\n\014GroupMessage\022)\n\tdata_type\030\001 \001(\0162\026.G" +
      "roupMessage.DataType\022\035\n\010customer\030\002 \001(\0132\t" +
      ".CustomerH\000\022\023\n\003car\030\003 \001(\0132\004.CarH\000\")\n\010Data" +
      "Type\022\020\n\014CustomerType\020\000\022\013\n\007CarType\020\001B\n\n\010d" +
      "ataBody\"$\n\010Customer\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030" +
      "\002 \001(\t\"$\n\003Car\022\016\n\006clueId\030\001 \001(\005\022\r\n\005title\030\002 " +
      "\001(\tB%\n\030com.sky.hiwise.netty.tcpB\007Message" +
      "H\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GroupMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GroupMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupMessage_descriptor,
        new java.lang.String[] { "DataType", "Customer", "Car", "DataBody", });
    internal_static_Customer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Customer_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Car_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Car_descriptor,
        new java.lang.String[] { "ClueId", "Title", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
